### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by wimil** [Gemorroj/ginfo#15]
how can i get cpu usage, similar to Ram memory usage

**Comment by Gemorroj** [comment]
Hi.
```php
$ginfo = new \Ginfo\Ginfo();
$info = $ginfo->getInfo();
$generalInfo = $info->getGeneral();

\print_r($generalInfo->getLoad());
```
see https://github.com/Gemorroj/ginfo/blob/master/src/OS/Linux.php#L381 for details
Is should be like that:
```
Array
(
    [0] => 0.16
    [1] => 0.03
    [2] => 0.01
)
```
But now supports only Linux.
